######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 30 20:15:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += sqlitehandler.h
SOURCES += index.cpp searchengine.cpp sqlitehandler.cpp
